# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zgui.ui'
#
# Created: Tue May  7 15:29:22 2013
#      by: PyQt4 UI code generator 4.10
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_zGui(object):
    def setupUi(self, zGui):
        zGui.setObjectName(_fromUtf8("zGui"))
        zGui.resize(1063, 594)
        zGui.setMinimumSize(QtCore.QSize(800, 400))
        zGui.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(zGui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.formLayout_5 = QtGui.QFormLayout()
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.lblChan = QtGui.QLabel(self.groupBox_2)
        self.lblChan.setObjectName(_fromUtf8("lblChan"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblChan)
        self.cmbChan = QtGui.QComboBox(self.groupBox_2)
        self.cmbChan.setObjectName(_fromUtf8("cmbChan"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbChan)
        self.horizontalLayout_3.addLayout(self.formLayout_5)
        self.formLayout = QtGui.QFormLayout()
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.lblDev = QtGui.QLabel(self.groupBox_2)
        self.lblDev.setObjectName(_fromUtf8("lblDev"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblDev)
        self.cmbDev = QtGui.QComboBox(self.groupBox_2)
        self.cmbDev.setObjectName(_fromUtf8("cmbDev"))
        self.formLayout.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbDev)
        self.horizontalLayout_3.addLayout(self.formLayout)
        self.formLayout_4 = QtGui.QFormLayout()
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.lblTrig = QtGui.QLabel(self.groupBox_2)
        self.lblTrig.setObjectName(_fromUtf8("lblTrig"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblTrig)
        self.cmbTrig = QtGui.QComboBox(self.groupBox_2)
        self.cmbTrig.setObjectName(_fromUtf8("cmbTrig"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbTrig)
        self.horizontalLayout_3.addLayout(self.formLayout_4)
        self.formLayout_3 = QtGui.QFormLayout()
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.lblBuf = QtGui.QLabel(self.groupBox_2)
        self.lblBuf.setObjectName(_fromUtf8("lblBuf"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblBuf)
        self.cmbBuf = QtGui.QComboBox(self.groupBox_2)
        self.cmbBuf.setObjectName(_fromUtf8("cmbBuf"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbBuf)
        self.horizontalLayout_3.addLayout(self.formLayout_3)
        self.formLayout_2 = QtGui.QFormLayout()
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.lblCset = QtGui.QLabel(self.groupBox_2)
        self.lblCset.setObjectName(_fromUtf8("lblCset"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.LabelRole, self.lblCset)
        self.cmbCset = QtGui.QComboBox(self.groupBox_2)
        self.cmbCset.setObjectName(_fromUtf8("cmbCset"))
        self.formLayout_2.setWidget(0, QtGui.QFormLayout.FieldRole, self.cmbCset)
        self.horizontalLayout_3.addLayout(self.formLayout_2)
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout = QtGui.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.ckbNShow = QtGui.QCheckBox(self.groupBox)
        self.ckbNShow.setObjectName(_fromUtf8("ckbNShow"))
        self.gridLayout.addWidget(self.ckbNShow, 0, 0, 1, 1)
        self.ckbPoint = QtGui.QCheckBox(self.groupBox)
        self.ckbPoint.setObjectName(_fromUtf8("ckbPoint"))
        self.gridLayout.addWidget(self.ckbPoint, 0, 1, 1, 1)
        self.ckbContinuous = QtGui.QCheckBox(self.groupBox)
        self.ckbContinuous.setObjectName(_fromUtf8("ckbContinuous"))
        self.gridLayout.addWidget(self.ckbContinuous, 0, 2, 1, 1)
        self.btnAcq = QtGui.QPushButton(self.groupBox)
        self.btnAcq.setObjectName(_fromUtf8("btnAcq"))
        self.gridLayout.addWidget(self.btnAcq, 1, 2, 1, 1)
        self.gridLayout_2.addWidget(self.groupBox, 1, 1, 1, 1)
        self.zTab = QtGui.QTabWidget(self.centralwidget)
        self.zTab.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.zTab.setObjectName(_fromUtf8("zTab"))
        self.tabDev = QtGui.QWidget()
        self.tabDev.setObjectName(_fromUtf8("tabDev"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.tabDev)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.scrl_dev_attr = QtGui.QScrollArea(self.tabDev)
        self.scrl_dev_attr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_dev_attr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_dev_attr.setWidgetResizable(True)
        self.scrl_dev_attr.setObjectName(_fromUtf8("scrl_dev_attr"))
        self.scrl_dev_attr_cont = QtGui.QWidget()
        self.scrl_dev_attr_cont.setGeometry(QtCore.QRect(0, 0, 297, 495))
        self.scrl_dev_attr_cont.setObjectName(_fromUtf8("scrl_dev_attr_cont"))
        self.gridLayout_3 = QtGui.QGridLayout(self.scrl_dev_attr_cont)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.gridLayout_3.setRowStretch(0, 30)
        self.scrl_dev_attr.setWidget(self.scrl_dev_attr_cont)
        self.horizontalLayout.addWidget(self.scrl_dev_attr)
        self.zTab.addTab(self.tabDev, _fromUtf8(""))
        self.tabCset = QtGui.QWidget()
        self.tabCset.setObjectName(_fromUtf8("tabCset"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.tabCset)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.scrl_cset_attr = QtGui.QScrollArea(self.tabCset)
        self.scrl_cset_attr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_cset_attr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_cset_attr.setWidgetResizable(True)
        self.scrl_cset_attr.setObjectName(_fromUtf8("scrl_cset_attr"))
        self.scrl_cset_attr_cont = QtGui.QWidget()
        self.scrl_cset_attr_cont.setGeometry(QtCore.QRect(0, 0, 297, 495))
        self.scrl_cset_attr_cont.setObjectName(_fromUtf8("scrl_cset_attr_cont"))
        self.gridLayout_4 = QtGui.QGridLayout(self.scrl_cset_attr_cont)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.scrl_cset_attr.setWidget(self.scrl_cset_attr_cont)
        self.horizontalLayout_2.addWidget(self.scrl_cset_attr)
        self.zTab.addTab(self.tabCset, _fromUtf8(""))
        self.tabBuf = QtGui.QWidget()
        self.tabBuf.setObjectName(_fromUtf8("tabBuf"))
        self.verticalLayout = QtGui.QVBoxLayout(self.tabBuf)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.scrl_buf_attr = QtGui.QScrollArea(self.tabBuf)
        self.scrl_buf_attr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_buf_attr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_buf_attr.setWidgetResizable(True)
        self.scrl_buf_attr.setObjectName(_fromUtf8("scrl_buf_attr"))
        self.scrl_buf_attr_cont = QtGui.QWidget()
        self.scrl_buf_attr_cont.setGeometry(QtCore.QRect(0, 0, 297, 495))
        self.scrl_buf_attr_cont.setObjectName(_fromUtf8("scrl_buf_attr_cont"))
        self.gridLayout_5 = QtGui.QGridLayout(self.scrl_buf_attr_cont)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.scrl_buf_attr.setWidget(self.scrl_buf_attr_cont)
        self.verticalLayout.addWidget(self.scrl_buf_attr)
        self.zTab.addTab(self.tabBuf, _fromUtf8(""))
        self.tabTrig = QtGui.QWidget()
        self.tabTrig.setObjectName(_fromUtf8("tabTrig"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.tabTrig)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.scrl_trg_attr = QtGui.QScrollArea(self.tabTrig)
        self.scrl_trg_attr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_trg_attr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_trg_attr.setWidgetResizable(True)
        self.scrl_trg_attr.setObjectName(_fromUtf8("scrl_trg_attr"))
        self.scrl_trg_attr_cont = QtGui.QWidget()
        self.scrl_trg_attr_cont.setGeometry(QtCore.QRect(0, 0, 297, 495))
        self.scrl_trg_attr_cont.setObjectName(_fromUtf8("scrl_trg_attr_cont"))
        self.gridLayout_6 = QtGui.QGridLayout(self.scrl_trg_attr_cont)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.scrl_trg_attr.setWidget(self.scrl_trg_attr_cont)
        self.verticalLayout_2.addWidget(self.scrl_trg_attr)
        self.zTab.addTab(self.tabTrig, _fromUtf8(""))
        self.tabChan = QtGui.QWidget()
        self.tabChan.setObjectName(_fromUtf8("tabChan"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.tabChan)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.scrl_chan_attr = QtGui.QScrollArea(self.tabChan)
        self.scrl_chan_attr.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scrl_chan_attr.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scrl_chan_attr.setWidgetResizable(True)
        self.scrl_chan_attr.setObjectName(_fromUtf8("scrl_chan_attr"))
        self.scrl_chan_attr_cont = QtGui.QWidget()
        self.scrl_chan_attr_cont.setGeometry(QtCore.QRect(0, 0, 297, 495))
        self.scrl_chan_attr_cont.setObjectName(_fromUtf8("scrl_chan_attr_cont"))
        self.gridLayout_7 = QtGui.QGridLayout(self.scrl_chan_attr_cont)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.scrl_chan_attr.setWidget(self.scrl_chan_attr_cont)
        self.verticalLayout_3.addWidget(self.scrl_chan_attr)
        self.zTab.addTab(self.tabChan, _fromUtf8(""))
        self.gridLayout_2.addWidget(self.zTab, 0, 0, 3, 1)
        self.gridLayout_2.setColumnStretch(0, 40)
        self.gridLayout_2.setColumnStretch(1, 60)
        zGui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(zGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1063, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        zGui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(zGui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        zGui.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(zGui)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        zGui.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(zGui)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(zGui)
        self.zTab.setCurrentIndex(4)
        QtCore.QMetaObject.connectSlotsByName(zGui)

    def retranslateUi(self, zGui):
        zGui.setWindowTitle(_translate("zGui", "MainWindow", None))
        self.groupBox_2.setTitle(_translate("zGui", "Objects", None))
        self.lblChan.setText(_translate("zGui", "Channels", None))
        self.lblDev.setText(_translate("zGui", "Devices", None))
        self.lblTrig.setText(_translate("zGui", "Trigger", None))
        self.lblBuf.setText(_translate("zGui", "Buffer", None))
        self.lblCset.setText(_translate("zGui", "Csets", None))
        self.groupBox.setTitle(_translate("zGui", "Acquisition", None))
        self.ckbNShow.setText(_translate("zGui", "Show all channel", None))
        self.ckbPoint.setText(_translate("zGui", "Show points", None))
        self.ckbContinuous.setText(_translate("zGui", "Continuous acquisition", None))
        self.btnAcq.setText(_translate("zGui", "Acquire", None))
        self.zTab.setTabText(self.zTab.indexOf(self.tabDev), _translate("zGui", "Device", None))
        self.zTab.setTabText(self.zTab.indexOf(self.tabCset), _translate("zGui", "Channel Sets", None))
        self.zTab.setTabText(self.zTab.indexOf(self.tabBuf), _translate("zGui", "Buffer", None))
        self.zTab.setTabText(self.zTab.indexOf(self.tabTrig), _translate("zGui", "Trigger", None))
        self.zTab.setTabText(self.zTab.indexOf(self.tabChan), _translate("zGui", "Channels", None))
        self.menuFile.setTitle(_translate("zGui", "File", None))
        self.toolBar.setWindowTitle(_translate("zGui", "toolBar", None))
        self.actionExit.setText(_translate("zGui", "Exit", None))
        self.actionExit.setShortcut(_translate("zGui", "Ctrl+Q", None))

