# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'zgui.ui'
#
# Created: Thu Dec  6 16:37:56 2012
#      by: PyQt4 UI code generator 4.9.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_zGui(object):
    def setupUi(self, zGui):
        zGui.setObjectName(_fromUtf8("zGui"))
        zGui.resize(1024, 768)
        zGui.setDockOptions(QtGui.QMainWindow.AllowTabbedDocks|QtGui.QMainWindow.AnimatedDocks)
        self.centralwidget = QtGui.QWidget(zGui)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.cmbCset = QtGui.QComboBox(self.centralwidget)
        self.cmbCset.setGeometry(QtCore.QRect(90, 50, 121, 25))
        self.cmbCset.setObjectName(_fromUtf8("cmbCset"))
        self.lblCset = QtGui.QLabel(self.centralwidget)
        self.lblCset.setGeometry(QtCore.QRect(20, 50, 60, 25))
        self.lblCset.setObjectName(_fromUtf8("lblCset"))
        self.lblChan = QtGui.QLabel(self.centralwidget)
        self.lblChan.setGeometry(QtCore.QRect(20, 170, 60, 25))
        self.lblChan.setObjectName(_fromUtf8("lblChan"))
        self.cmbChan = QtGui.QComboBox(self.centralwidget)
        self.cmbChan.setGeometry(QtCore.QRect(90, 170, 121, 25))
        self.cmbChan.setObjectName(_fromUtf8("cmbChan"))
        self.zTab = QtGui.QTabWidget(self.centralwidget)
        self.zTab.setGeometry(QtCore.QRect(20, 400, 991, 301))
        self.zTab.setObjectName(_fromUtf8("zTab"))
        self.tabDev = QtGui.QWidget()
        self.tabDev.setObjectName(_fromUtf8("tabDev"))
        self.zTab.addTab(self.tabDev, _fromUtf8(""))
        self.tabCset = QtGui.QWidget()
        self.tabCset.setObjectName(_fromUtf8("tabCset"))
        self.zTab.addTab(self.tabCset, _fromUtf8(""))
        self.tabBuf = QtGui.QWidget()
        self.tabBuf.setObjectName(_fromUtf8("tabBuf"))
        self.zTab.addTab(self.tabBuf, _fromUtf8(""))
        self.tabTrig = QtGui.QWidget()
        self.tabTrig.setObjectName(_fromUtf8("tabTrig"))
        self.zTab.addTab(self.tabTrig, _fromUtf8(""))
        self.tabChan = QtGui.QWidget()
        self.tabChan.setObjectName(_fromUtf8("tabChan"))
        self.zTab.addTab(self.tabChan, _fromUtf8(""))
        self.cmbDev = QtGui.QComboBox(self.centralwidget)
        self.cmbDev.setGeometry(QtCore.QRect(90, 10, 121, 25))
        self.cmbDev.setObjectName(_fromUtf8("cmbDev"))
        self.lblDev = QtGui.QLabel(self.centralwidget)
        self.lblDev.setGeometry(QtCore.QRect(20, 10, 60, 25))
        self.lblDev.setObjectName(_fromUtf8("lblDev"))
        self.lblBuf = QtGui.QLabel(self.centralwidget)
        self.lblBuf.setGeometry(QtCore.QRect(20, 90, 60, 25))
        self.lblBuf.setObjectName(_fromUtf8("lblBuf"))
        self.cmbBuf = QtGui.QComboBox(self.centralwidget)
        self.cmbBuf.setGeometry(QtCore.QRect(90, 90, 121, 25))
        self.cmbBuf.setObjectName(_fromUtf8("cmbBuf"))
        self.lblTrig = QtGui.QLabel(self.centralwidget)
        self.lblTrig.setGeometry(QtCore.QRect(20, 130, 60, 25))
        self.lblTrig.setObjectName(_fromUtf8("lblTrig"))
        self.cmbTrig = QtGui.QComboBox(self.centralwidget)
        self.cmbTrig.setGeometry(QtCore.QRect(90, 130, 121, 25))
        self.cmbTrig.setObjectName(_fromUtf8("cmbTrig"))
        self.graph = QtGui.QGraphicsView(self.centralwidget)
        self.graph.setGeometry(QtCore.QRect(250, 10, 761, 371))
        self.graph.setObjectName(_fromUtf8("graph"))
        self.btnAcq = QtGui.QPushButton(self.centralwidget)
        self.btnAcq.setGeometry(QtCore.QRect(90, 210, 120, 25))
        self.btnAcq.setObjectName(_fromUtf8("btnAcq"))
        self.ckbNShow = QtGui.QCheckBox(self.centralwidget)
        self.ckbNShow.setGeometry(QtCore.QRect(20, 250, 150, 25))
        self.ckbNShow.setObjectName(_fromUtf8("ckbNShow"))
        self.ckbPoint = QtGui.QCheckBox(self.centralwidget)
        self.ckbPoint.setGeometry(QtCore.QRect(20, 290, 150, 25))
        self.ckbPoint.setObjectName(_fromUtf8("ckbPoint"))
        zGui.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(zGui)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        zGui.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(zGui)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        zGui.setStatusBar(self.statusbar)
        self.toolBar = QtGui.QToolBar(zGui)
        self.toolBar.setObjectName(_fromUtf8("toolBar"))
        zGui.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionExit = QtGui.QAction(zGui)
        self.actionExit.setObjectName(_fromUtf8("actionExit"))
        self.menuFile.addAction(self.actionExit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(zGui)
        self.zTab.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(zGui)

    def retranslateUi(self, zGui):
        zGui.setWindowTitle(QtGui.QApplication.translate("zGui", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.lblCset.setText(QtGui.QApplication.translate("zGui", "Csets", None, QtGui.QApplication.UnicodeUTF8))
        self.lblChan.setText(QtGui.QApplication.translate("zGui", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.zTab.setTabText(self.zTab.indexOf(self.tabDev), QtGui.QApplication.translate("zGui", "Device", None, QtGui.QApplication.UnicodeUTF8))
        self.zTab.setTabText(self.zTab.indexOf(self.tabCset), QtGui.QApplication.translate("zGui", "Channel Sets", None, QtGui.QApplication.UnicodeUTF8))
        self.zTab.setTabText(self.zTab.indexOf(self.tabBuf), QtGui.QApplication.translate("zGui", "Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.zTab.setTabText(self.zTab.indexOf(self.tabTrig), QtGui.QApplication.translate("zGui", "Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.zTab.setTabText(self.zTab.indexOf(self.tabChan), QtGui.QApplication.translate("zGui", "Channels", None, QtGui.QApplication.UnicodeUTF8))
        self.lblDev.setText(QtGui.QApplication.translate("zGui", "Devices", None, QtGui.QApplication.UnicodeUTF8))
        self.lblBuf.setText(QtGui.QApplication.translate("zGui", "Buffer", None, QtGui.QApplication.UnicodeUTF8))
        self.lblTrig.setText(QtGui.QApplication.translate("zGui", "Trigger", None, QtGui.QApplication.UnicodeUTF8))
        self.btnAcq.setText(QtGui.QApplication.translate("zGui", "Acquire", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbNShow.setText(QtGui.QApplication.translate("zGui", "Show all channel", None, QtGui.QApplication.UnicodeUTF8))
        self.ckbPoint.setText(QtGui.QApplication.translate("zGui", "Show points", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("zGui", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.toolBar.setWindowTitle(QtGui.QApplication.translate("zGui", "toolBar", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setText(QtGui.QApplication.translate("zGui", "Exit", None, QtGui.QApplication.UnicodeUTF8))
        self.actionExit.setShortcut(QtGui.QApplication.translate("zGui", "Ctrl+Q", None, QtGui.QApplication.UnicodeUTF8))

